test-alt-p8:
  image: alt:p8
  script:
  - apt-get update -yqq
  - apt-get install git -yqq
  - apt-get install -yqq
    libudev-devel
    awesome
    xorg-xephyr
    qt5-base-common
    qt5-base-devel
    make guile20
    qt5-tools
  - qmake-qt5
  - make -j$(nproc)
  - make -j$(nproc) check

test-alt-p10:
  image: alt:p10
  script:
  - apt-get update -yqq
  - apt-get install -yqq
    git
    guile22-devel
    texinfo
    autoconf_2.60
    automake
    make
    gettext
    gettext-tools
    awesome
    docker-ce
    lightdm
    libqt5-core
    libtool
    qt5-base-devel
    qt5-tools
    libudev-devel
    virtualgl
    Xdialog
    guile22
  - qmake-qt5
  - make -j$(nproc)
  - make -j$(nproc) check

test-ubuntu-20.04:
  image: ubuntu:20.04
  script:
  - apt update -yqq
  - apt install -yqq
    autoconf
    automake
    docker.io
    libudev-dev
    libxfixes-dev
    lightdm
    lightdm-gtk-greeter
    awesome
    build-essential
    qt5-default
    qtbase5-dev
    qttools5-dev-tools
    guile-2.2
    guile-2.2-dev
    texinfo
    gettext
    make
  - qmake-qt5
  - make -j$(nproc)
  - make -j$(nproc) check
