#!/bin/bash

# Add a new seat SEAT_MUM
add_seat() {
    local seat_num="$1"
    dm-tool add-local-x-seat "$seat_num"
}

# Start LightDM with a given CONFIG_FILE
start_lightdm() {
    local config_file="$1"
    lightdm --config "$config_file" &
    sleep 1
}

###

# Entry point.
main() {
    local seat_count="$1"
    local idx
    start_lightdm "/root/src/mst/etc/lightdm-mst.conf"

    for idx in $(seq 1 "$seat_count"); do
	add_seat $idx
    done

    while true; do
	sleep 1
    done
}

main $*
