#!/bin/bash -x

SEAT_NUMBER=$(echo "$DISPLAY" | sed -re 's/:([0-9]+)\.[0-9]+.*/\1/g')
DIRECTORY="${USER}_${SEAT_NUMBER}"

Xdialog --yesno "Отключить флеш-накопитель?"  10 40
if [ $? -eq 0 ]; then
    sudo umount $DIRECTORY
fi
