#!/bin/bash

### mst-start-dm -- Start LightDM and add seats.

# Copyright (C) 2018 Artyom V. Poptsov <poptsov.artyom@gmail.com>
#
# This file is part of MST.
#
# MST is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# MST is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with MST.  If not, see <http://www.gnu.org/licenses/>.

###

# Add a new seat SEAT_MUM
add_seat() {
    local seat_num="$1"
    /usr/bin/dm-tool add-local-x-seat "$seat_num"
}

# Start LightDM with a given CONFIG_FILE
start_lightdm() {
    local config_file="$1"
    /usr/sbin/lightdm --config "$config_file" &
    sleep 1
}

# Check if a seat is used.
#
# Synopsis:
#   seat_is_used_p display_id
is_seat_used_p() {
    local id="$1"
    [ $(who | grep -cE ".*\(:$id\).*") = "0" ] \
	&& echo "false" || echo "true"
}

###

# Entry point.
main() {
    local seat_count="$1"
    local idx
    local running_seats_number
    start_lightdm "/etc/lightdm/lightdm-mst.conf"

    xset -dpms
    xset s off

    for idx in $(seq 1 "$seat_count"); do
	add_seat $idx
    done

    while true; do
	running_seats_number=$(/usr/bin/dm-tool list-seats | grep -c "Seat")
	if [ $running_seats_number -lt $seat_count ]; then
	    for idx in $(seq 1 "$seat_count"); do
		if [ "$(is_seat_used_p $idx)" = "false" ]; then
		    ls -1 /proc | grep -E "[0-9]+" | while read pid; do
			res=$(grep "DISPLAY=:$idx" \
				   "/proc/$pid/environ" > /dev/null 2>&1; \
			      echo $?)
			if [ $res -eq 0 ]; then
			    kill "$pid"
			fi
		    done
		    add_seat $idx
		fi
	    done
	fi
	sleep 1
    done
}

main $*

### mst-start-dm ends here.
