#!/bin/bash

# Add a new seat SEAT_MUM
add_seat() {
    local seat_num="$1"
    /usr/bin/dm-tool add-local-x-seat "$seat_num"
}

# Start LightDM with a given CONFIG_FILE
start_lightdm() {
    local config_file="$1"
    /usr/sbin/lightdm --config "$config_file" &
    sleep 1
}

# Check if a seat is used.
#
# Synopsis:
#   seat_is_used_p display_id
is_seat_used_p() {
    local id="$1"
    [ $(who | grep -cE ".*\(:$id\).*") = "0" ] \
	&& echo "false" || echo "true"
}

###

# Entry point.
main() {
    local seat_count="$1"
    local idx
    local running_seats_number
    start_lightdm "/etc/lightdm/lightdm-mst.conf"

    xset -dpms
    xset s off

    for idx in $(seq 1 "$seat_count"); do
	add_seat $idx
    done

    while true; do
	running_seats_number=$(/usr/bin/dm-tool list-seats | grep -c "Seat")
	if [ $running_seats_number -lt $seat_count ]; then
	    pkill --full '/usr/sbin/lightdm-gtk-greeter'
	    for idx in $(seq 1 "$seat_count"); do
		if [ "$(is_seat_used_p $idx)" = "false" ]; then
		    add_seat $idx
		fi
	    done
	fi
	sleep 1
    done
}

main $*
