#!/bin/bash

### DEBUG

# exec 1> /tmp/u.log
# exec 2>&1
# set -x

###

get_user_by_display_number() {
    local display_number="$1"
    local user=$(who | grep "(:$display_number)" \
		     | sed -re 's/^([^ ]+) +:[0-9]+.*/\1/g')
    echo "$user"
}

make_mount_dir() {
    local mount_dir="$1"
    local user="$2"
    [ -e "$mount_dir" ] || mkdir "$mount_dir"
    sudo chown -R "$user:" "$mount_dir"
}

### Entry point.

main() {
    local device="$1"
    local display_number="$2"
    local user=$(get_user_by_display_number "$display_number")
    local user_id=$(id --user "$user")
    local group_id=$(id --group "$user")
    local mount_dir="/media/${user}_${display_number}"
    make_mount_dir "$mount_dir" "$user"

    sudo /bin/mount -o users,noauto,umask=0022,uid="$user_id",gid="$group_id" \
	 "$device" "$mount_dir"
}

main $*

### mst-mount ends here.
